[profile.default]
src = 'src'
out = 'src/out'
libs = ["node_modules", "lib"]
libraries = ['src/contracts/libraries/CheqBase64Encoding.sol:CheqBase64Encoding:0x6cC614e8a7f83df4a85e4cCCaCE7fcd71576fE9D', 
             'src/contracts/libraries/DataTypes.sol:DataTypes:0x912ef5c235c22f09eC98d476E52A0725d54Abc11', 
             'src/contracts/libraries/Errors.sol:Errors:0x0e49a5311cDccD7EC733710686Da89B6C7b48F3C', 
             'src/contracts/libraries/Events.sol:Events:0x9628ab62198EE35ad7fBAD47cdF463eD8a1464a3']
gas_reports = ["src/contracts/Cheq.sol"]
optimizer = true
optimizer-runs = 10_000_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config